# Generated by Django 4.1.7 on 2023-06-11 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(max_length=20, null=True)),
                ('profile_pics', models.ImageField(default='', null=True, upload_to='pics')),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20, null=True)),
                ('state_of_origin', models.CharField(max_length=100, null=True)),
                ('lga_origin', models.CharField(max_length=100, null=True)),
                ('scheme_name', models.CharField(max_length=100, null=True)),
                ('residential_address', models.CharField(max_length=100, null=True)),
                ('state_of_residence', models.CharField(max_length=20, null=True)),
                ('lga_residence', models.CharField(max_length=100, null=True)),
                ('highest_level_of_education', models.CharField(choices=[('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('DEGREE', 'DEGREE'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=50, null=True)),
                ('id_type', models.CharField(choices=[('NATIONAL IDENTIFICATION CARD', 'NATIONAL IDENTIFICATION CARD'), ('VOTERS CARD', 'VOTERS CARD'), ('DRIVERS LICENSE', 'DRIVERS LICENSE'), ('PASSPORT', 'PASSPORT')], max_length=100, null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('id_image', models.ImageField(upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
