# Generated by Django 4.1.7 on 2023-06-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scheme_name',
        ),
    ]
