# Generated by Django 4.1.7 on 2023-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_highest_level_of_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_names',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Unspecified')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_of_residence',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
